### ISSUE TITLE
Minimum temperature

### ISSUE THREAD

**Issue by acelot** [paranerd/xiaomi_heater#1]
Hi, thank you for your integration, this is the only integration that works with my heaters!

I have a question, is it possible to set the temperature below 18°C? I want to keep my country's house temperature near 14-15°C when I'm in the city.

**Comment by paranerd** [comment]
Hi, thank you!

However, I am no longer actively using/maintaining this solution. I'm waiting for [this repo](https://github.com/rytilahti/python-miio) to publish a new release which should then be used in the official Xiaomi Integration. For the meantime I switched to [this Integration](https://github.com/al-one/hass-xiaomi-miot) which works just fine for me.

Sorry but hope this helps you out!

**Comment by acelot** [comment]
Oh, OK, thank you for the link!
